VERSION 0.8
FROM scratch

# save-base-image saves the test image (that have all the test sources)
# as deskpro/docker-product-base:test. Useful if you want to run the
# image manually for some reason.
#
# Example usage:
#  earthly +save-base-image
#  docker run --rm -it deskpro/docker-product-base:test bash
save-base-image:
    FROM +base-image
    SAVE IMAGE deskpro/docker-product-base:test

# test runs all tests
test:
    WAIT
        BUILD +test-serverspec-web
        BUILD +test-serverspec-opc
        BUILD +test-serverspec-simple-cases
        BUILD +test-custom-configs
        BUILD +test-custom-logs-group
        BUILD +test-smokescreen
        BUILD +test-opcache-override
    END
    WAIT
        BUILD +test-autoinstall
    END
    WAIT
        BUILD +test-automigrations
    END

# test-serverspec-web runs serverspec tests against the base image in web mode
# with no customization options enabled. That is, these specs apply against
# a pristine environment when not even basic conifg has been provided.
test-serverspec-web:
    FROM earthly/dind:alpine
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN docker run -d --name test deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/always spec/default_web' \
            && docker stop test \
            && docker start test \
            && echo "Run again to verify state after rebooting" \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/always spec/default_web'
    END

# test-serverspec-opc runs opc specific tests
# TODO - currently just runs same as +test-serverspec-web but in opc mode
test-serverspec-opc:
    FROM earthly/dind:alpine
    COPY --dir serverspec/spec/scenarios/bc_opc_2_8/deskpro_dir /tmp/deskpro_dir
    COPY --dir serverspec/spec/scenarios/bc_opc_2_8/test_helper_tools /tmp/test_helper_tools
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN docker run -d --name test \
            -e OPC_VERSION=2.8.0 \
            -v /tmp/deskpro_dir:/deskpro \
            -v /tmp/test_helper_tools:/test_helper_tools \
            deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/bc_opc_2_8/01_opc_bc.rb' \
            && docker stop test \
            && docker start test \
            && echo "Run again to verify state after rebooting" \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/always spec/default_web spec/scenarios/bc_opc_2_8/01_opc_bc.rb'
    END

# test-serverspec-simplecases runs serverspec tests against the base image in web mode
# to test 'simple' test cases. These are cases that don't require any special setup.
test-serverspec-simple-cases:
    FROM earthly/dind:alpine
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN docker run -d --name test deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/cases/simple'
    END

# test-autoinstall checks the behaviour of AUTO_RUN_INSTALLER=true to ensure
# the installer runs when it should, and that it doesn't run when it shouldn't.
test-autoinstall:
    FROM earthly/dind:alpine
    # this test relies on simulating the installer based on a sentinel file
    # that is cleared after the instsalation has run.
    RUN mkdir /tmp/sim && touch /tmp/sim/needs-installer
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN \
            # first run - simulate that the installer needs to run
            docker run -d --name test \
                -e AUTO_RUN_INSTALLER=true \
                -v /tmp/sim:/run/sim \
                deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/autoinstall/01_installer_spec.rb' \
            && docker stop test \
            # second run - verify that the installer doesn't run again
            && docker start test \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/autoinstall/02_post_installer_spec.rb'
    END

# test-automigrations checks the behaviour of AUTO_RUN_MIGRATIONS=true to ensure
# the installer runs when it should.
test-automigrations:
    FROM earthly/dind:alpine
    # this test relies on simulating the installer based on a sentinel file
    # that is cleared after the instsalation has run.
    RUN mkdir /tmp/sim && touch /tmp/sim/needs-migrations
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN \
            # first run - simulate that the migrations need to run
            docker run -d --name test \
                -e AUTO_RUN_MIGRATIONS=true \
                -v /tmp/sim:/run/sim \
                deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/automigrations/01_migrations_spec.rb' \
            && docker stop test \
            # second run - verify that migrations doesn't run again
            && docker start test \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/automigrations/02_post_migrations_spec.rb'
    END

# test-custom-configs checks the behaviour of mounting custom config files via /deskpro/config/ dirs.
test-custom-configs:
    FROM earthly/dind:alpine
    COPY --dir serverspec/spec/scenarios/custom_configs/deskpro_dir /tmp/deskpro-dir
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN \
            # first run - simulate that the migrations need to run
            docker run -d --name test \
                -v /tmp/deskpro-dir:/deskpro \
                deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/custom_configs/01_custom_configs_spec.rb' \
            && docker stop test \
            && rm /tmp/deskpro-dir/config/php.d/* \
            && docker start test \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/custom_configs/02_custom_configs_removed_spec.rb'
    END

test-custom-logs-group:
    FROM earthly/dind:alpine
    RUN addgroup --gid 1988 logs_group \
        && mkdir /tmp/deskpro-logs \
        && chown root:logs_group /tmp/deskpro-logs \
        && chmod 0775 /tmp/deskpro-logs
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN \
            docker run -d --name test \
                -e CONTAINER_NAME=logtest \
                -e LOGS_GID=1988 \
                -e FAST_SHUTDOWN=0 \ # need to disable fast shutdown so vector has time to write log file we're testing
                -v /tmp/deskpro-logs:/deskpro/logs \
                deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/custom_log_group/01_custom_log_group_spec.rb' \
            && docker exec test /usr/bin/php -r 'echo $doesNotExist; /* this causes an error to be logged */' \
            && docker stop test
    END
    RUN echo "/tmp/deskpro-logs/logtest-php-error.log should be owned by logs_group" && stat /tmp/deskpro-logs/logtest-php-error.log | grep 1988

# test-opcache-override checks that the PHP_OPCACHE_* sizing env vars are
# applied to the rendered php ini.
test-opcache-override:
    FROM earthly/dind:alpine
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN \
            docker run -d --name test \
                -e PHP_OPCACHE_MAX_ACCELERATED_FILES=12345 \
                -e PHP_OPCACHE_MEMORY_CONSUMPTION=256 \
                -e PHP_OPCACHE_INTERNED_STRINGS_BUFFER=48 \
                deskpro/docker-product-base:test web \
            && docker exec test /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/opcache_override' \
            && docker stop test
    END

# test-smokescreen checks the smokescreen egress proxy: the
# DISABLE_DESKPRO_PROXY_SERVICE switch (default true: daemon + env vars off; false: both on), and the operator
# config-file override (mounted via /deskpro/config/smokescreen.d/).
test-smokescreen:
    FROM earthly/dind:alpine
    COPY --dir serverspec/spec/scenarios/smokescreen/deskpro_dir /tmp/deskpro-dir
    COPY --dir serverspec/spec/scenarios/smokescreen/dump_cfg_fixtures /tmp/dump-cfg-fixtures
    WITH DOCKER --load deskpro/docker-product-base:test=+base-image
        RUN \
            docker run -d --name test-disabled \
                -e DISABLE_DESKPRO_PROXY_SERVICE=true \
                deskpro/docker-product-base:test web \
            && docker exec test-disabled /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/01_smokescreen_disabled_spec.rb' \
            && docker stop test-disabled \
            && docker run -d --name test-override \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -e SMOKESCREEN_CONFIG_FILE=/etc/smokescreen/custom.yaml \
                -v /tmp/deskpro-dir:/deskpro \
                deskpro/docker-product-base:test web \
            && docker exec test-override /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/02_smokescreen_override_spec.rb' \
            && docker stop test-override \
            && docker run -d --name test-no-proxy \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -e DESKPRO_DB_HOST=dbhost.internal \
                -e NO_PROXY=operator-extra.internal \
                deskpro/docker-product-base:test web \
            && docker exec test-no-proxy /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/03_smokescreen_no_proxy_derivation_spec.rb' \
            && docker stop test-no-proxy \
            && docker run -d --name test-no-proxy-urls \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -e DESKPRO_ES_URL=https://es.internal:9200 \
                -e DESKPRO_ES_TIKA_HOST=http://tika.internal:9998 \
                -e DESKPRO_REDIS_URL=redis://redis.internal:6379/0 \
                -e OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector.internal:4318 \
                deskpro/docker-product-base:test web \
            && docker exec test-no-proxy-urls /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/04_smokescreen_no_proxy_url_hosts_spec.rb' \
            && docker stop test-no-proxy-urls \
            && docker run -d --name test-dump-cfg-full \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -v /tmp/dump-cfg-fixtures/dump-cfg-full:/srv/deskpro/serve/bin/dump-cfg \
                deskpro/docker-product-base:test web \
            && docker exec test-dump-cfg-full /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/05_smokescreen_config_php_merge_spec.rb' \
            && docker stop test-dump-cfg-full \
            && docker run -d --name test-dump-cfg-nonzero \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -e DESKPRO_DB_HOST=dbhost.internal \
                -v /tmp/dump-cfg-fixtures/dump-cfg-nonzero:/srv/deskpro/serve/bin/dump-cfg \
                deskpro/docker-product-base:test web \
            && docker exec test-dump-cfg-nonzero /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/06_smokescreen_config_php_nonzero_fallback_spec.rb' \
            && docker stop test-dump-cfg-nonzero \
            && docker run -d --name test-dump-cfg-malformed \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -e DESKPRO_DB_HOST=dbhost.internal \
                -v /tmp/dump-cfg-fixtures/dump-cfg-malformed:/srv/deskpro/serve/bin/dump-cfg \
                deskpro/docker-product-base:test web \
            && docker exec test-dump-cfg-malformed /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/07_smokescreen_config_php_malformed_fallback_spec.rb' \
            && docker stop test-dump-cfg-malformed \
            && docker run -d --name test-disable-false \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                deskpro/docker-product-base:test web \
            && docker exec test-disable-false /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/08_smokescreen_disable_false_spec.rb' \
            && docker stop test-disable-false \
            && docker run -d --name test-svc-override-under-disable \
                -e DISABLE_DESKPRO_PROXY_SERVICE=true \
                -e SVC_SMOKESCREEN_ENABLED=true \
                deskpro/docker-product-base:test web \
            && docker exec test-svc-override-under-disable /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/09_smokescreen_svc_override_under_disable_spec.rb' \
            && docker stop test-svc-override-under-disable \
            && docker run -d --name test-svc-override-disabled \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -e SVC_SMOKESCREEN_ENABLED=false \
                deskpro/docker-product-base:test web \
            && docker exec test-svc-override-disabled /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/10_smokescreen_svc_override_disabled_spec.rb' \
            && docker stop test-svc-override-disabled \
            && docker run -d --name test-dump-cfg-partial \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -v /tmp/dump-cfg-fixtures/dump-cfg-partial:/srv/deskpro/serve/bin/dump-cfg \
                deskpro/docker-product-base:test web \
            && docker exec test-dump-cfg-partial /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/11_smokescreen_config_php_absent_keys_spec.rb' \
            && docker stop test-dump-cfg-partial \
            && docker run -d --name test-noproxy-boot-order \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -v /tmp/dump-cfg-fixtures/dump-cfg-noproxy-wiring-probe:/srv/deskpro/serve/bin/dump-cfg \
                deskpro/docker-product-base:test web \
            && docker exec test-noproxy-boot-order /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/12_smokescreen_no_proxy_boot_order_spec.rb' \
            && docker stop test-noproxy-boot-order \
            && docker run -d --name test-enabled \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                deskpro/docker-product-base:test web \
            && docker exec test-enabled /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/13_smokescreen_enabled_spec.rb' \
            && docker stop test-enabled \
            && docker run -d --name test-external-proxy \
                -e DISABLE_DESKPRO_PROXY_SERVICE=true \
                -e DESKPRO_HTTPS_PROXY=http://egress.example:3128 \
                -e DESKPRO_DB_HOST=dbhost.internal \
                deskpro/docker-product-base:test web \
            && docker exec test-external-proxy /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/14_smokescreen_external_proxy_spec.rb' \
            && docker stop test-external-proxy \
            && docker run -d --name test-external-proxy-precedence \
                -e DISABLE_DESKPRO_PROXY_SERVICE=false \
                -e DESKPRO_HTTPS_PROXY=http://egress.example:3128 \
                deskpro/docker-product-base:test web \
            && docker exec test-external-proxy-precedence /bin/sh -c 'cd /test/serverspec && rspec spec/scenarios/smokescreen/15_smokescreen_external_proxy_precedence_spec.rb' \
            && docker stop test-external-proxy-precedence
    END

# Built on top of the product base image, this just adds test sources
# and simulation sources used when testing various container features.
base-image:
    FROM DOCKERFILE -f ../Dockerfile ../
    RUN DEBIAN_FRONTEND=noninteractive apt-get update \
        && apt-get install --no-install-recommends --no-install-suggests -y ruby iproute2 \
        && rm -rf /var/lib/apt/lists/* \
        && gem install bundler serverspec rake
    ENV BOOT_LOG_LEVEL=TRACE
    ENV BOOT_LOG_LEVEL_EXEC=TRACE
    ENV HTTP_USE_TESTING_CERTIFICATE=true
    ENV FAST_SHUTDOWN=true
    COPY --dir serverspec /test/serverspec
    COPY --dir simulate-release/* /srv/deskpro
    RUN \
        echo "true" > /run/is-container-test \
        && cd /test/serverspec \
        && bundler install
