# nginx access logs
[sources.nginx_access_raw]
type = "file"
include = ["/var/log/nginx/access.log", "/var/log/log/nginx/access.log.1"]
ignore_not_found = true

[transforms.nginx_access]
type = "remap"
inputs = ["nginx_access_raw"]
source = '''
if is_string(.message) && contains(string!(.message), get_env_var!("VECTOR_MARKER")) {
  abort
}

.log_group = "nginx-access"
.app = "nginx"
.chan = "access"
.lvl = "INFO"

.parsed = parse_json!(.message)
.parsed.msg = ""

if !is_nullish(.parsed.ts) {
  .ts = parse_timestamp(.parsed.ts, "%+") ?? null
}

status_int = int(.parsed.status) ?? 200
if status_int >= 500 {
  .lvl = "ERROR"
} else if status_int >= 400 {
  .lvl = "NOTICE"
}
'''

# nginx error logs
[sources.nginx_error_raw]
type = "file"
include = ["/var/log/nginx/error.log", "/var/log/nginx/error.log.1"]
ignore_not_found = true

[transforms.nginx_error]
type = "remap"
inputs = ["nginx_error_raw"]
source = '''
if is_string(.message) && contains(string!(.message), get_env_var!("VECTOR_MARKER")) {
  abort
}

.log_group = "nginx-error"
.app = "nginx"
.chan = "error"
.parsed = parse_nginx_log(.message, "error") ?? {}
'''
