#!/bin/bash

# This command is run every 60 seconds (see conf.d/logging.conf rotate_logs event listener)
# This will read log files and rotate them from mylog.log to mylog.log.1 if they are 10MB or larger.
#
# This is because the logs in the filesystem are only meant to be temporary buffers.
#
# Vector is used to process and ship the logs elsewhere. Most commonly this will
# be by outputting all logs to stdout (e.g. for docker logs) or to output them
# to a directory (e.g. for onprem who wants to manage them with logrotate etc).
#
# In any case, the actual logs kept in the container at any given time is minimal.

printf "READY\n"

while read -r header; do
  echo "$header" >&2
  bytes=$(echo "$header" | sed 's/.*\://')
  read -r -n "$bytes" event
  echo "$event" >&2

  find /var/log -type f -name '*.log' -size +10M -not -path /var/log/docker-logs | while read f; do
    echo "Rotating $f ($(stat -c%s "$f"))" >&2
    copy "$f" "$f.1"
    echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] Log file started: $f -- ${VECTOR_MARKER}" > "$f"
  done

  # always correct log files in /var/log/deskpro
  # (e.g. if someone ran script as root it could create a *new* log file)
  find /var/log/deskpro -type f -name '*.log' -not -user dp_app | while read f; do
    chown dp_app:adm "$f"
  done

  printf "RESULT 2\nOK"
  printf "READY\n"
done < /dev/stdin
