#!/bin/bash
docker buildx create --name multiarch --driver docker-container --use
docker buildx build --platform linux/arm64,linux/amd64 --build-arg BUILDKIT_MULTI_PLATFORM=1 -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .
